str mapinfo[56][12] = {
{
"Training Mission","Mars","STR_MAP_STR01","Deadline (Intro)","4","N/A","N/A","P_STR01",
"Welcome to the training course. Here, you will be pitted against holographic",
"renditions of Hell's weakest minions to get a taste of what awaits on the",
"real battlefields. Don't be afraid, the holo-demons aren't able to harm you.",
"Lt. Carmack will give you further briefing on the premise of deadline defense."
},
{
"Tier 1, Mission 1","Mars","STR_MAP_STR02","Deadline","10","$100","4","P_STR02",
"This will be your first major stronghold defense mission, marine. Here,",
"you'll encounter the weakest of Hell's forces, but that doesn't mean you",
"won't still have to be on your toes at all times - the difficulty mounts",
"rapidly, so put all you've learned in training to the test!"
},
{
"Tier 1, Mission 2","Sigma Two","STR_MAP_STR03","Deadline","10","$200","6","P_STR03",
"The acidic lakes surrounding the perimeter of our strongholds on this planet are",
"bathing holes for demons. Expect the demon numbers to be high and the task of",
"successfully defending this stronghold to be taxing for the amateur defender.",
"And be sure not to plummet into the acid."
},
{
"Tier 1, Mission 3","Maelstrom","STR_MAP_STR04","Deadline","10","$300","5","P_STR04",
"This volatile nebula houses a single UAC stronghold. Even so, it's a crucial research",
"outpost, and its scientists wish to study the unique phenomena that occur within",
"this maelstrom. Research that could revolutionize UAC gateway technology is being",
"conducted here, so it is vital that this facility doesn't fall to the legions of Hell."
},
{
"Tier 1, Mission 4","Crimson","STR_MAP_STR05","Deadline","10","$400","6","P_STR05",
"This dark mountain peak is home to a minute UAC stronghold. Demons are approaching from",
"the planet's ground level from all directions, and aerial assaults from steadily growing",
"demonic swarms are to be expected. It will be easy to let even the weakest demon cross the",
"deadline, so you'll have to secure the stronghold entrance as tightly as possible."},

{"Tier 1, Mission 5","Earth","STR_MAP_STR06","Core (Intro)","10","$500","6","P_STR06",
"Our beloved homeworld is rarely safe from demon invasion, especially one on a galactic",
"scale. Possessed humans, now slaves to the demonic empire of Hell, roam our streets,",
"laying out a swath of destruction, while Hell sends out its heavy militia towards a",
"crucial UAC control point - a computer core station. Defend it with your life!"},

{"Tier 2, Mission 1","Null X-1","STR_MAP_STR07","Core","10","$600","6","P_STR07",
"This barren planet seems to be devoid of any humanoid life, hence the name. Even so, the",
"demons have chosen to wage an attack on a recently abandoned core facility which, as it",
"turns out, may prove useful in future UAC endeavors after all. Restore hope to this",
"forsaken planet and protect the computer core at all costs!"},

{"Tier 2, Mission 2","Gorge","STR_MAP_STR08","Core","10","$700","5","P_STR08",
"What was once an island paradise is now a demon-infested hellhole. This planet was",
"a widely-famed holiday resort for intergalactic tourists, at least before the demons",
"landed. Expect heavy resistance to come from all directions towards your stronghold.",
""},

{"Tier 2, Mission 3","Herros","STR_MAP_STR09","Core","4","$800","4","P_STR09",
"This storage facility is situated in extremely hostile territory. Swarms of hellspawn",
"are approaching, and the hazardous lava-filled caverns make for demon breeding",
"grounds. Defending this stronghold will be a tricky undertaking, and be prepared",
"for the worst, whatever that might be."},

{"Tier 2, Mission 4","Cyclone","STR_MAP_STR10","Core","10","$900","7","P_STR10",
"This research substation, orbiting the planet Cyclone, is one of many that links",
"to the main orbital research nexus, also in orbit over the planet. If the demons",
"succeed in severing this vital connection, the UAC research network may suffer a",
"crippling blow. Be sure to use the station's defensive ion cannon to your advantage."},

{"Tier 2, Mission 5","Skorpid","STR_MAP_STR11","Milestone (Intro)","10","$1000","6","P_STR11",
"This stronghold is a truly massive structure, one of the UAC's finest, so it's",
"expected that the demons will be attacking it in equally monstrous waves. You",
"will have to change your tactics somewhat to ensure the complete security of",
"this stronghold. See Lt. Carmack for further briefing."},

{"Tier 3, Mission 1","Skorpid","STR_MAP_STR12","Deadline","10","$1100","7","P_STR12",
"A planet as dry and barren as the Sahara, although the demons seem to relish in such",
"conditions. They are advancing on this tiny stronghold in large numbers, and seek",
"its immediate destruction. A hazardous task is ahead of you, but you as a marine",
"are expected to serve the UAC by defending it with your life!"},

{"Tier 3, Mission 2","Maelstrom","STR_MAP_STR13","Deadline","10","$1200","6","P_STR13",
"Deep within the underground caverns of this fiery asteroid, all hell is quite",
"literally breaking loose. This is not so much a stronghold as simply a very large",
"mining excavation, where we have uncovered the remains of a hellish temple. Quite",
"obviously, the demon swarms will be flourishing here, so stay totally sharp."},

{"Tier 3, Mission 3","Ormantium","STR_MAP_STR14","Deadline","10","$1300","7","P_STR14",
"This space station in high orbit over the planet Ormantium is under attack from",
"heavily-armed demon/cyborg onslaughts. Such invaders require heavy-duty weaponry",
"to take down, so you'll be provided with plenty of rockets for most of this mission.",
"You may, however, also require a certain amount of luck to get through unscathed..."},

{"Tier 3, Mission 4","Styx","STR_MAP_STR15","Core","10","$1400","7","P_STR15",
"On this chaotic planet, where fire rains from the constantly stormy sky,",
"demons from the foulest of Hell's pits are trying to overrun a vital computer",
"station situated on a charred, rocky ridge. The conditions are hostile and the",
"monsters are many, but you must still do your utmost to hold them back!"},
 
{"Tier 3, Mission 5","Cerberus","STR_MAP_STR16","Limit (Intro)","8","$1500","8","P_STR16",
"This bitterly cold planet houses a vast, powerful UAC stronghold. It could stand",
"a large scale assault from the demonic army of Hell, at least for a while, but",
"the massive waves of monsters advancing still pose a threat. This mission will",
"test your mettle for crowd control to the limit - literally."},
 
{"Tier 4, Mission 1","Sigma Two","STR_MAP_STR17","Core","10","$1600","6","P_STR17",
"The dismal planet of Sigma Two is not one of the most preferable locales for a",
"considerably-sized defense stronghold such as this one, but unfortunately, the demon",
"waves approaching it are sufficient enough in number to level it completely. We",
"can't suffer a loss that great, so it's up to you to make this mission a success."},
 
{"Tier 4, Mission 2","Midnat II","STR_MAP_STR18","Limit","10","$1700","7","P_STR18",
"An abandoned defense bunker that was utterly stormed during the last demon invasion.",
"Some of its defensive utilities are still intact, though you won't have many places",
"to hide, and even fewer chances to hold the advancing waves back. Do all you can under",
"the circumstances to stop the hellspawn from destroying it!"},

{"Tier 4, Mission 3","Styx","STR_MAP_STR19","Limit","10","$1800","7","P_STR19",
"This demonic edifice houses a gateway leading directly to our supercluster. Many",
"brave soldiers have lost their lives trying to stabilize this sector, but despite",
"their efforts, hordes of demons are still trying to take back the gateway. They will",
"wreak havoc upon our homeworlds if we lose control of it. It's all up to you."},

{"Tier 4, Mission 4","Heloxyd","STR_MAP_STR20","Limit","7","$1900","7","P_STR20",
"This dilapidated UAC warehouse was abandoned a while ago when deadly toxins from",
"the planet's underground began seeping into it. While the toxins were eventually",
"contained, the same can't be said for the hordes of fast, deadly demons that",
"endanger this stronghold. Defending this base sure won't be a walk in the park."},

{"Tier 4, Mission 5","Midnat II","STR_MAP_STR21","Overmind (Intro)","10","$2000","5","P_STR21",
"This cold planet, lit only by the spooky aura of its moons, has already been",
"overrun by the legions of Hell. An enormous, demonic lifeform has been reported",
"causing untold chaos on our main control tower stronghold here - so in order to",
"survive, you may have to drastically change your strategies."},

{"Tier 5, Mission 1","Rouger","STR_MAP_STR22","Deadline","10","$2100","5","P_STR22",
"This planet is embraced by an elusive orange fog. A small stronghold has been",
"constructed here to allow further study of the various other environmental",
"oddities of this planet. The demons will be arriving to invade every nook and",
"cranny of this stronghold - so be alert."},
 
{"Tier 5, Mission 2","Chlorine","STR_MAP_STR23","Milestone","11","$2200","6","P_STR23",
"This is another massive UAC stronghold, constructed within the acidic mines of the",
"planet Chlorine. There are many vital control points inside the stronghold itself,",
"and if the invaders manage to take out all of them, the facility is as good as dead.",
"Beware though, the monsters are fast and powerful, so use everything at your disposal."},
 
{"Tier 5, Mission 3","Midnat II","STR_MAP_STR24","Limit","10","$2300","8","P_STR24",
"This power facility's energy conductors project beautiful lights into the atmosphere",
"that illuminate the surrounding area. Unfortunately, the intense lights have attracted",
"the attention of the more powerful legions of Hell. Expect heavy resistance from all",
"sides, and guard the exposed main teleporter at any cost!"},
 
{"Tier 5, Mission 4","Mars","STR_MAP_STR25","Overmind","10","$2400","6","P_STR25",
"The demons are planning an assault on a major Martian defense installation, which",
"houses a powerful electromagnetic jammer, designed to prevent demons from storming",
"the planet's surface. The Overmind has been reincarnated not far from this stronghold",
"with intent to destroy its exterior core network - it must be kept intact!"},
 
{"Tier 5, Mission 5","Deep Space","STR_MAP_STR26","Goals (Intro)","16","$2500","4","P_STR26",
"This substantial space station is the hub of the UAC's inter-planetary research network.",
"Its massive data terminals house crucial information on all of the military branches",
"and strongholds in this sector. Exabytes of precious data is at stake. Protect every",
"single square inch of this station, or all will be lost."},
 
{"Tier 6, Mission 1","Cyclone","STR_MAP_STR27","Milestone","8","$2600","6","P_STR27",
"The skies of this elusive planet are constantly dancing with the aurora borealis",
"phenomenon, as it is known on Earth, and luminous crystals dot the landscape.",
"This planet is falling rapidly under the demons' influence - and what would",
"otherwise be a visually bountiful planet is turning into a satanic cesspool."},

{"Tier 6, Mission 2","Skorpid","STR_MAP_STR28","Goals","7","$2700","6","P_STR28",
"Our terraforming station on this planet is being surrounded on all sides by demon",
"invaders. In the wrong hands, the experimental terraformer device could cause",
"irreversible damage. You must defend it, AND keep it stable, to prevent the demons",
"from wresting control of the entire planet."},

{"Tier 6, Mission 3","Jailba","STR_MAP_STR29","Limit","11","$2800","7","P_STR29",
"This stronghold is situated in a floodplain on the planet Jailba. The arrival of the",
"demons to this site has caused some massive atmospheric disturbances, so the weather",
"conditions have harshened dramatically and all personnel have evacuated before the",
"inevitable flood strikes. The demons will be numerous this time, so gear up well."},

{"Tier 6, Mission 4","Deep Space","STR_MAP_STR30","Limit","7","$2900","N/A","P_STR30",
"Somehow, on this immense asteroid, the demons have unearthed a dimensional slipgate",
"that will allow them to jump lightyears at a time. If they are allowed to rampage all",
"across the universe, then humanity will surely be doomed. Be prepared for the worst,",
"marine, and block their entrance through the gate through any means necessary!"},

{"Tier 6, Mission 5","Null X-1","STR_MAP_STR31","Core","10","$3000","7","P_STR31",
"Welcome back to this barren wasteland of a planet, marine. This time, our oil-mining",
"stronghold has been placed in jeopardy by the spawning hordes of monsters. The core",
"powering the heavy mining machinery, which if destroyed could render the entire",
"facility useless, is unfortunately badly exposed. You must not fail us here."},

{"Tier 6, Mission 6","Crimson","STR_MAP_STR32","Limit","11","$3100","8","P_STR32",
"This planet has been renowned amongst UAC explorers and researchers for having many",
"paradoxical phenomena. It boasts several somewhat peculiar structures, including this",
"floating fortress, which the UAC is beginning to study in greater depth. However,",
"the area is already rife with demons, so expect the unexpected."},

{"Tier 6, Mission 7","Photon","STR_MAP_STR33","Milestone","11","$3200","6","P_STR33",
"The thick purple fog engulfing the UAC control point in this nebula will only hinder",
"you, so we've provided you with a few extra temporary means of defense that may aid you",
"in holding off the demonic army, while you attempt to navigate the complex structure of",
"this stronghold. We wish you luck - this will by no means be an easy task."},

{"Tier 6, Mission 8","Rouger","STR_MAP_STR34","Goals","13","$3300","8","P_STR34",
"This planet's thin atmosphere and dangerous proximity to its lethally radioactive",
"sun make it a hazardous environment. Storms rage violently across its surface,",
"and a hefty battalion of demons encroaches a series of control towers situated in",
"a particularly hostile area of the planet. Use caution, there's more than one way to die..."},

{"Final Mission","Mars","STR_MAP_STR35","Goals","21","N/A","9","P_STR35",
"???",
"",
"",
""},

{},{},{},{},

{"Familiar Mission 1","Crimson","STR_MAP_STR40","Limit","10","$3000","7","P_STR40",
"Much like Midnat II, this planet houses a defense bunker that has been abandoned.",
"With its still working technology, it will be useful to us, but the demons will try",
"to get to it through the caves. Make sure you don't let your guard down as you hold",
"the demons off."},

{"Familiar Mission 2","Null X-1","STR_MAP_STR41","Deadline","10","$3000","5","P_STR41",
"The demons are attacking one of our main defense installations here on Null X-1. We have",
"already lost the station's ion cannon amidst the chaos of their previous attack, and it",
"is likely they will make use of it during the course of this mission. You must prevent",
"the demons from destroying this base and stealing more of its destructive weaponry."},

{"Familiar Mission 3","Crimson","STR_MAP_STR42","Deadline","10","$3000","6","P_STR42",
"This planet has been renowned amongst UAC explorers and researchers for having many",
"paradoxical phenomena. It boasts several somewhat peculiar structures, including this",
"floating fortress, which the UAC is beginning to study in greater depth. However,",
"the area is already rife with demons, so expect the unexpected."},

{"Familiar Mission 4","Sigma Two","STR_MAP_STR43","Core","12","$3000","7","P_STR43",
"The dismal planet of Sigma Two is not one of the most preferable locales for a",
"considerably-sized defense stronghold such as this one, but unfortunately, the demon",
"waves approaching it are sufficient enough in number to level it completely. We",
"can't suffer a loss that great, so it's up to you to make this mission a success."},

{"Familiar Mission 5","Deep Space","STR_MAP_STR44","Limit","9","$3000","N/A","P_STR44",
"Demonic influence on this sector of Deep Space has caused space itself to tear apart,",
"made clear from the twisted nature of the physical terrain itself. If the demons are",
"not stopped here, then all of space-time itself could be at risk of annihilation.",
"Marine, be prepared to stop the demons through any means necessary!"},

{},{},{},{},{},

{"Secret Mission 1","Earth","STR_MAP_STR50","Save The Babes","10","$1500","5","P_STR50",
"An alien invasion is taking place on Earth, but not one like any we've seen before.",
"Some merciless aliens have invaded the streets of Los Angeles, destroying",
"the city, converting its population into monstrous abominations, and abducting",
"our babes. It's time to nuke those son-of-a-bitches hard."},

{},

{"Secret Mission 2","Earth","STR_MAP_STR52","Limit","10","$1500","5","P_STR52",
"All hell has broken loose. The dead rise, the sky falls, and twisted, satanic",
"magicks are abundant. Worse still, nightmarish ghouls rampage through our towns,",
"their demented influence corrupting the very fabric of our world. Doomsday is at",
"hand, and your speed and wile will be tested to the limit."},

{},

{"Secret Mission 3","Hell","STR_MAP_STR54","Goals","10","$1500","6","P_STR54",
"While hellspawn rampaged on Earth, the UAC launched their remaining task force against",
"the final demon gate in a bid to close it from the other side. One brave marine stood",
"up, and overthrew the hellish legions single-handedly. In a recreation of this",
"historic battle, your mission is to seal the gate, and secure the control points."},

{},

{"Secret Mission 4","Phobos","STR_MAP_STR56","Core","10","$1500","5","P_STR56",
"The mining facilities on Phobos revealed this huge, ancient stargate under the moon's",
"surface. Just after your arrival, the gate opened and let loose hundreds of demons and",
"zombies. Your task here is to defend the interior of the mining base from this somewhat",
"familiar onslaught. Will you succeed where your predecessors failed?"},

};




#define MAXMONSTERS 49
str MonsterNames[MAXMONSTERS] = {
"Former Human",
"Former Human Sergeant",
"Former Human Commando",
"Former Human Rocketeer",
"Former Human Plasma Gunner",
"Dune Warrior",
"Suicide Bomber",
"Zombie Tank",
//
"Imp",
"Dark Imp",
"Phase Imp",
"Shadow",
"Catharsi",
//
"Bull Demon (AKA Pinky)",
"Mech Demon / Blood Demon",
"Nightmare Demon",
//
"Lost Soul",
"Guardian Cube",
"Hades Sphere",
"Wicked",
//
"Cacodemon",
"Enhanced Cacodemon",
"Cacolantern",
"Nightmare Cacodemon",
"Abaddon",
"Pain Elemental",
"Hades Elemental",
//
"Revenant",
//
"Satyr",
"Hell Knight",
"Baron of Hell",
"Belphegor",
"Hell Warrior",
"Bruiser Demon",
"Cyber Baron / Cybruiser",
"Archon of Hell",
"Pyro Demon",
"Azazel",
//
"Mancubus",
"Hectebus",
//
"Arachnotron",
"Fusion Cannon Arachnotron",
//
"Hellion",
"Arch-Vile",
"Diabolist",
//
"Spider Mastermind",
"Spider Demolisher",
"Cyberdemon",
"Terminator",
};

// \cu dark gray <=50Very Low
// \ch blue <=100Low
// \cd green <=300Medium
// \cf gold <=500Medium High
// \ci orange <=1000High
// \cg red <=3000Very High
// \ca brick >3000Insane

str MonsterStats[MAXMONSTERS][9] = {
{"HoloDeco_ZombieMan","\cu20","\chSlow","\cuVery Low","Undead","Hitscan","$1-3","None","S. Priestess"},
{"HoloDeco_ShotgunGuy","\cu30","\chSlow","\chLow","Undead","Hitscan","$2-4","None","S. Priestess"},
{"HoloDeco_Chaingunner","\ch60","\chSlow","\cdMedium","Undead","Hitscan (Continuous)","$3-6","None","S. Priestess"},
{"HoloDeco_RocketTrooper","\cu50","\chSlow","\cdMedium","Undead","Projectile","$3-5","None","W. Weasel"},
{"HoloDeco_ZombieMan","\cu50","\chSlow","\cdMedium","Undead","Projectile","$3-5","None","R. West"},
{"HoloDeco_DuneWarrior","\cd120","\chSlow","\cdMedium","Undead","Projectile and Hitscan","$5-8","Cloak","J. Paddock"},
{"HoloDeco_SuicideBomber","\ch80","\cgFast","\cdMedium","Undead","Melee Only","$4","Kamikaze","W. Weasel"},
{"HoloDeco_ZombieTank","\ci600","\cgFast","\cdMedium","Undead/Mechanical","Hitscan (Semi-Continuous)","$12","None","J. Paddock"},
// 8
{"HoloDeco_Imp","\ch60","\chSlow","\chLow","Demon","Projectile and Melee","$3-6","None","J. Paddock"},
{"HoloDeco_PhaseImp","\cd120","\chSlow","\chLow","Demon","Projectile and Melee","$5-8","None","R. West"},
{"HoloDeco_PhaseImp","\cd150","\ca???","\cfMedium High","Demon/Mutation","Tracer and Melee","$6-9","Phase","J. Paddock"},
{"HoloDeco_Shadow","\ch80","\cgFast","\cdMedium","Demon","Projectile (Continuous)","$4-7","None","B. V. Ostmann"},
{"HoloDeco_Catharsi","\cd120","\chSlow","\cdMedium","Alien","Projectile","$5-8","Bomb","W. Weasel"},
// 13
{"HoloDeco_Demon","\cd150","\cfQuick","\cdMedium","Demon","Melee Only","$6","None","W. Weasel"},
{"HoloDeco_BloodDemon","\cd300","\cgFast","\cdMedium","Demon/Cyborg","Melee Only","$8","None","W. Weasel"},
{"HoloDeco_NightmareDemon","\cd260","\cgFast","\cfMedium High","Demon/Nightmare","Projectile and Melee","$8","Stealth","J. Paddock"},
// 16
{"HoloDeco_LostSoul","\ch100","\cgFast","\cdMedium","Demon","Charge","$4","Flight","W. Weasel & S. Priestess"},
{"HoloDeco_GuardianCube","\ch80","\cfQuick","\cdMedium","Unknown","Projectile","$5","Flight","J. Paddock"},
{"HoloDeco_HS","\cu35","\cfQuick","\cfMedium High","Unknown","Melee Only","$2","Flight, Phase, Kamikaze","J. Paddock"},
{"HoloDeco_Wicked","\cd275","\chSlow","\cdMedium","Demon","Projectile","$8","Flight","J. Paddock"},
// 20
{"HoloDeco_Cacodemon","\cf400","\chSlow","\cdMedium","Demon","Projectile and Melee","$9","Flight","B. V. Ostmann"},
{"HoloDeco_EnhancedCaco","\cd300","\chSlow","\cdMedium","Demon/Mutation","Projectile and Melee","$10","Flight","W. Weasel"},
{"HoloDeco_Cacodemon","\ci800","\chSlow","\cfMedium High","Demon","Projectile and Melee","$13","Flight","R. West"},
{"HoloDeco_Cacodemon","\ci700","\cfQuick","\cfMedium High","Demon/Nightmare","Projectile and Melee","$14","Flight","R. West"},
{"HoloDeco_EnhancedCaco","\cg1200","\cfQuick","\ciHigh","Demon","Projectile and Melee","$17","Flight","T. Samaho"},
{"HoloDeco_PainElemental","\cf400","\chSlow","\cfMedium High","Demon","Spawn","$10","Flight, Death Spawn","W. Weasel"},
{"HoloDeco_Helemental","\cg1600","\chSlow","\cgVery High","Demon","Lightning, Projectile, Summon, Melee","$30","Flight, Phase","J. Paddock"},
// 27
{"HoloDeco_Revenant","\cd300","\cfQuick","\cfMedium High","Undead","Projectile, Tracer, and Melee","$12","None","S. Priestess"},
// 28
{"HoloDeco_HellKnight","\cf400","\chSlow","\cdMedium","Demon","Melee","$10","None","R. West"},
{"HoloDeco_HellKnight","\cf500","\chSlow","\cdMedium","Demon","Projectile and Melee","$11","None","S. Priestess"},
{"HoloDeco_BaronOfHell","\ci1000","\chSlow","\cdMedium","Demon","Projectile and Melee","$15","None","S. Priestess"},
{"HoloDeco_BaronOfHell","\cg1500","\chSlow","\cfMedium High","Demon","Projectile and Melee","$19","None","T. Samaho"},
{"HoloDeco_HellWarrior","\cf400","\chSlow","\cfMedium High","Demon","Projectile and Melee","$14","Shield","J. Paddock"},
{"HoloDeco_BruiserDemon","\cg1500","\chSlow","\cgVery High","Demon","Projectile, Floor Hugger","$27","None","W. Weasel"},
{"HoloDeco_Cybruiser","\cg2000","\chSlow","\cfMedium High","Demon/Cyborg","Projectile and Melee","$22","None","W. Weasel"},
{"HoloDeco_ArchonOfHell","\cg2000","\chSlow","\cgVery High","Demon","Projectile and Melee","$32","None","W. Weasel"},
{"HoloDeco_PyroDemon","\cg2500","\chSlow","\caInsane!","Demon","Teleport, Melee, Projectile (Explosive)","$36","Teleportation","S. Scream"},
{"HoloDeco_Azazel","\cg2400","\chSlow","\caInsane!","Demon","Super Tracers, Projectile, Melee, Counter Attack","$48","Counter Attack and Healing","J. Paddock"},
// 38
{"HoloDeco_Fatso","\ci600","\chSlow","\cfMedium High","Demon/Cyborg","Projectile","$12","None","W. Weasel"},
{"HoloDeco_Hectebus","\cg1500","\chSlow","\ciHigh","Demon/Cyborg","Projectile","$18","None","J. Paddock"},
// 40
{"HoloDeco_Arachnotron","\cf500","\chSlow","\cfMedium High","Demon/Cyborg","Projectile (Continuous)","$12","None","S. Priestess"},
{"HoloDeco_FusionSpider","\ci600","\chSlow","\ciHigh","Demon/Cyborg","Projectile (Continuous)","$12","None","J. Paddock"},
// 42
{"HoloDeco_Hellion","\ch70","\cfQuick","\cdMedium","Demon","Projectile","$4-8","None","M. Orpheus"},
{"HoloDeco_Archvile","\ci700","\cgFast","\ciHigh","Demon","Distance","$18","Resurrection","S. Priestess"},
{"HoloDeco_Diabolist","\cg1400","\cgFast","\cgVery High","Demon","Projectile, Tracer, Distance","$25","None","J. Paddock"},
// 45
{"HoloDeco_Mastermind","\cg3000","\chSlow","\ciHigh","Demon/Cyborg","Hitscan (Continuous)","$45","None","W. Weasel"},
{"HoloDeco_Demolisher","\ca6000","\chSlow","\cgVery High","Demon/Cyborg","Projectile and Hitscan (Continuous)","$55","None","W. Weasel"},
{"HoloDeco_Cyberdemon","\ca4000","\cfQuick","\ciHigh","Demon/Cyborg","Projectile (Explosive)","$40","None","S. Priestess"},
{"HoloDeco_Terminator","\ca7000","\chSlow","\caInsane!","Cyborg","\cgEVERYTHING!","$60","Unstoppable","B. V. Ostmann"},
// 49
};

str MonsterBio[MAXMONSTERS][8] ={
//---ZOMBIES---//
//Zombieman
{"The weakest and most common enemy. All they have is a rifle, and they're",
"really a poor shot. They're only really a threat in large groups, but even",
"then, they probably cause more collateral damage than they'll do to you. They",
"don't put up much of a fight if you shoot them down quickly enough.","","","",""},
//Shotgun Guy
{"A step up from the zombieman; this guy wields a shotgun. He is still not too",
"tough, but he'll get you good if you let your guard down.","","","","","",""},
//Chaingunner
{"Kill from a distance if you can. This guy's weapon will pulverize you in",
"seconds if you don't have suitable cover. If he's involved in a crossfire, he",
"will usually win because his attacks are so painful that they cause other",
"demons to slow down.","","","",""},
//Rocket Zombie
{"These men were once members of our anti-tank battalions. They carry the same",
"kind of rocket launcher as you, and pack a gigantic punch if you're not",
"careful. While they go down easy - they're only human, after all - it may be",
"more worthwhile to leave them alive for a while to let them accidentally fire",
"their weapons at larger monsters.","","",""},
//Plasma Zombie
{"Much like the other former humans, these guys will go down easily. Sadly, they",
"carry a plasma rifle, and while they don't fire it as fast as you do, it will",
"still incinerate you if you aren't careful. It is advised to not let them fire",
"upon you when you fight them. Worse still, they only drop an energy cell upon",
"death, rather than a plasma rifle.","","",""},
//Dune Warrior
{"These guys were once some of our most elite stealth units, trained to brave",
"the harshest of climates. Their flame bomb launcher and semi-automatic",
"machine gun are nothing to get too concerned about, because they also possess a",
"cloaking device, allowing them to bypass your defense belt virtually unseen",
"until it wears off. Their Achilles' heel is their low health, so if you suspect",
"they're around, throw a rocket into an open space and watch any of them nearby",
"go flying.",""},
//Suicide Bomber
{"A possessed soldier wired up with high explosives. His main goal in life is to",
"run towards something destructible and then detonate himself. He's rather hard",
"to miss; his insane screaming is quite loud and you'll probably hear it from a",
"pretty far distance. Interestingly, though, the souls Hell has chosen to",
"become kamikazes were evidently those of people who killed themselves",
"similarly in their previous life. I guess if they did one thing well, they",
"could always do it again...",""},
//Zombie Tank
{"The zombies left with enough brain capacity to retain their driving skills you",
"will see swerving around the battlefield in these well-armored UAC vehicles,",
"firing the mounted gatling guns in every direction. They can also accelerate to",
"high speeds and, as a result, capture the objective with relative ease if you",
"give them sufficient opportunity. The trick is: Don't! Have a suitable weapon",
"on you and make sure to take them out from a distance - destroying them causes",
"them to explode in a ball of flame, causing minor damage to everything nearby.",""},
//---IMPS---//
//Imp
{"Forget little dwarf faeries with pick-axes - the real demon is very different.",
"Imps are probably Hell's expendable worker drones, with fire-summoning attacks",
"that aren't terribly powerful but threatening all the same, especially when",
"they emerge in massive groups, which they often do. Because they're rather",
"weak, it's easy to take them out with a powerful weapon, so make sure you have",
"one ready in case they choose to bring a few hundred or so of their buddies",
"along with them.",""},
//Dark Imp
{"A variation on the demonic imp, these are only slightly less common than the",
"regular imp. Much like the regular imp, they are an expendable \"trash\" monster,",
"so to speak, and they aren't that tough alone, but tend to appear in groups.",
"However, this variant on the imp has twice as much health, which means you'll want",
"a better weapon than a shotgun to take them out. In addition to that, they also",
"shoot fireballs that are purple and move MUCH faster than the normal imp ones, so",
"taking caution is somewhat advised. Worse, they look almost exactly like the",
"phase imp (mentioned later)."},
//Phase Imp
{"Among the adjectives used to describe the phase imp are: Fast, durable,",
"deadly, and annoying. Phase imps appear to be a sort of mutated form of the",
"dark imp, and unfortunately more than twice as threatening as their lesser",
"counterparts. Once you hear that bone-chilling war cry, be sure to terminate",
"them quickly, if you can; they can take a heavy amount of shots before biting",
"the dirt. If you don't, they will disappear in front of you, before",
"teleporting beyond the objective and possibly ending your mission in failure.",
"Make sure you have cover from their homing attacks as well."},
//Shadow
{"This sneaky little stalker may appear weak at first, and its relatively low",
"health seems to back this up. However, its high speed and its semi-transparent",
"flesh make this foe a much more serious threat, so stay on the lookout for",
"them as they can pass a defense line with ease. Facing a single shadow is",
"a very rare occurrence, as they ALWAYS appear in swarms of varying sizes.",
"", "", ""},
//Catharsi
{"Even extraterrestrial life believes in Hell, or at least a variant of it. The",
"catharsi don't appear to be demons themselves, but are certainly operating",
"under Hell's influence. Their dedication is such that, even when near death,",
"their only goal is the destruction of those who oppose them - watch out for",
"the floating detonators that they drop when they die. Skilled marines can use",
"these to their advantage, though, by killing one catharsi in a group of other",
"monsters to soften up the rest of them a bit.",""},
//---DEMONS---//
//Demon
{"The first relatively serious threat to new marines, the demon is fast and",
"powerful, and takes a beating. Presumably, the demon's origins come from the",
"departed souls of athletes who abused steroids, or perhaps they're the",
"deformed offspring of Hell's various nobles. Beware their speed; even if they",
"aren't coming for you, they will almost always be the ones to seize the gates.",
"Certain variants of these demons appear blurred to human eyes and are hard to",
"see effectively.",""},
//Blood Demon
{"Also nicknamed the \"steam demon\", the blood demon's craving for speed has",
"turned it towards cybernetics. Blood demons are unique for their bionic legs,",
"which they use to run very, very quickly. The downside to that is that they",
"make quite a racket when moving around, so if you happen to lose one, listen",
"for that signature clanking noise.","","",""},
//Nightmare Demon
{"By the time you've noticed a swarm of nightmare demons approaching your",
"objective, it's usually too late to stop 'em in time. These guys are insanely",
"fast, and regurgitate plasma balls similar to those hurled by the Hell nobles.",
"Not only that, but they turn semi-invisible when roaming, meaning you'll have",
"to despatch their numbers within seconds of spotting them. Because they",
"typically ambush strongholds in swarms, you'll have to have a weapon with a",
"high destructive capacity to make sure they're taken out with all speed.",""},
//---FLIERS---//
//Lost Soul
{"Hell's version of that hyper little puppy that never left you alone. When he",
"charges, he's going to be moving fast, so be ready with that itchy trigger",
"finger of yours, or you're going to have a hell of a time keeping this guy away",
"from the deadline! However, he's easy to dodge, and only poses a threat in",
"great numbers. A good tactic is to try to line them up so that when they",
"attack you, they bump into each other, or a nearby demon.","",""},
//Guardian Cube
{"The guardian cube is like a weak lost soul, but still annoying as hell. They",
"fly straight to their objective, being sure to brush away anything that they",
"see obscuring their goal. They have ranged attacks, too, which they will",
"launch constantly if their target is visible. Target immediately, and take",
"them down fast.","","",""},
//Hades Sphere
{"The Hades sphere is not really a demon, more like a ball of sentient bloodlust",
"that phases in and out of existence to fool its opposition, before appearing",
"in front of them again and self-destructing with extreme force. You won't",
"usually see these guys on your missions, so thank Heaven for that, but the",
"Hades elemental will vomit these guys out in twos, so if you can get a bead on",
"them, make it count, before the battlefield is swarmed by the bastards.","",""},
//Wicked
{"This peculiar snake-like apparition is like an especially annoying version of",
"the cacodemon. He will charge, using his whip-like tail to accelerate towards",
"his foe, and when within range, launch a homing fireball which will sooner",
"or later catch up with them. They are tougher than they appear, so be ready to",
"clash heads with them for lengthy periods if you don't have a suitable weapon.",
"","",""},
//---GASBALLS---//
//Cacodemon
{"One of the more common enemies you will face while holding back the demonic",
"forces. The cacodemon contains a mixture of various noxious gases within its",
"body, which not only enables it to hover through the air, but also lets it",
"project ignited balls of gas at its prey. The lack of extremities does not",
"mean that it is incapable of defending itself in close combat; the razor-sharp",
"teeth and muscular jaws can and will cut through you in an instant.","",""},
//Enhanced Cacodemon
{"So far as we can tell, these guys are pretty much the same as the cacodemons",
"you're used to seeing - helium-filled, projectile-spewing tomatoes. Except",
"these guys can shoot even more fireballs at once. The good part? They're no",
"harder to actually put down than your garden-variety cacodemon. Just, uh,",
"remember to stay out of their way.","","",""},
//Cacolantern
{"These are the older sibling of the cacodemons - sprouting a very distinct",
"orange color, much like the fires of Hell they were probably spawned from,",
"and they are very tough - they have twice as much health as the normal cacodemon,",
"and worse yet, shoot fireballs that travel twice as quickly. Their bite also is",
"more vicious - don't get too close.","","",""},
//Nightmare Cacodemon
{"These spectral monstrosities make the nightmare demon look nice. Moving faster",
"than the ordinary cacodemon, these blue and partially invisible nightmares will",
"shoot cacolantern fireballs, which travel much faster than cacodemon fireballs.",
"In addition to that, they shoot them out much faster than an ordinary cacodemon.",
"Adding to THAT is the fact that they are almost as tough as the cacolantern.","","",""},
//Abaddon
{"Arguably the worst part about the abaddon is that it looks almost exactly like",
"the enhanced cacodemon. But, dear God, it's not. It has THREE TIMES the health of",
"an ordinary cacodemon, shoots in twos, has a much lower pain chance, moves faster,",
"and shoots Hades projectiles (covered in the Hades elemental, mentioned later).",
"These guys are thankfully rare, but when they appear, you better be ready to",
"fight. They have a yellow eye, rather than the enhanced caco's red eye, so keep",
"an eye out.",""},
//Pain Elemental
{"The pain elemental combines the two most irritating things in the world:",
"Missiles, and lost souls. This floating head - which bears an odd resemblance",
"to those other floaty monsters - launches lost souls at high speeds. Guard the",
"base entrance carefully when these are around, because if they manage to shoot",
"a lost soul past your defenses, you're pretty much screwed. Oh, and be careful",
"where you kill them, too, because they leave behind even more lost souls when",
"they explode.",""},
//Hades Elemental
{"You may well have just met your maker. The Hades elemental is one of the most",
"powerful monsters you will encounter, with a deadly arsenal consisting of",
"lightning attacks, regurgitating Hades spheres, teleportation, and a mouth so",
"vast, it will swallow anything that happens near it. It takes quite a beating",
"before exploding in a shower of flaming debris (at which point, it will spawn",
"even more Hades spheres), so you are urged to ensure that you have an extremely",
"powerful firearm in your possession before confronting this behemoth.",""},
//---REVENANTS---//
//Revenant
{"Hell doesn't make waste. Take a dead demon, and strap on some armor and homing",
"rocket launchers, and you've got this fellow. He also likes to get up close",
"and personal, so watch out! He's moderately tough to kill.","","","","",""},
//---NOBLES---//
//Satyr
{"These minor nobles are just that - minor. They only have a melee attack, but",
"they attack faster than most demons, and do a lot of damage. They do have some",
"level of inherent toughness - but as long as you stay out of their range, they",
"shouldn't be a problem. Think of them like slower, but tougher blood demons.","","","",""},
//Hell Knight
{"A lesser version of the baron of Hell, this creature's skin is not quite as",
"flushed, and can only take half the amount of damage as their stronger cousins",
"before dying. They do, however, attack with the same type of plasma, so",
"caution is still highly advised against them.","","","",""},
//Baron of Hell
{"This creature has pinkish flushed skin over the top half of his body, and goat",
"legs on the bottom. The baron of Hell is not as common as some of the other",
"enemies, but that makes it no less of a threat. He hurls green plasma balls at",
"his target which can do moderate to severe damage. He's also pretty tough,",
"too, and it's going to take more than what it usually takes for other enemies",
"to put him down.","",""},
//Belphegor
{"A greater version of the baron of Hell, this creature has very distinct red",
"flushed skin over the top half of his body. The belphegor is not as common as",
"some of the other Hell nobles - notably the Hell knight and baron of Hell -",
"but you should be thankful for that. He's much tougher, possessing one and a half",
"times as much health as the baron, meaning that he'll be tougher to bring down.",
"His green plasma balls also travel much faster than other Hell nobles. Be careful",
"when confronting this beast.",""},
//Hell Warrior
{"The Hell warrior's monstrous visage is the first thing you'll notice. Then",
"you'll notice the huge metal shield he carries. And if you're not careful, you",
"won't be noticing much more after that. Despite only having 400 hit points",
"(that's less than a Hell knight), he's still a formidable adversary. His",
"shield blasts out flesh-rending energy projectiles, and he can absorb all",
"damage while the shield is raised in front of him. He has the standard noble",
"plasma attack, too.",""},
//Bruiserdemon
{"Ordinarily, we would advise you to run the hell away from these things, but",
"considering you're supposed to be defending outposts and not saving your own",
"skin, that is unfortunately not an option. So our best advice to you is: Take",
"cover! These guys have a spread fireball attack - which is highly deadly in close",
"range and is otherwise hard to dodge - a high damage focused fireball attack, but",
"its worst attack are these fiery spikes that travel across the ground.","",""},
//Cybruiser
{"You probably remember the Amish: Those Christian folks from Earth that ignored",
"technology in favor of simple lives and hard work. Well, after seeing",
"mechanical monstrosities like this, don't you wish Hell took a few pages from",
"their book? The cybruiser basically comes from the same mold as Hell's nobles,",
"but is enhanced with the latest advances (i.e. whatever they stole from the",
"last base we lost) in targeting systems and anti-vehicle weaponry. This guy",
"exemplifies why it's so important to guard the outposts in the first place -",
"to stop stuff like THIS from happening!"},
//Archon of Hell
{"This guy truly stands out from the rest of the Hell nobles - in more ways than",
"one. First off, he has an unmistakable black and red hide and boasts huge",
"spikes all down his upper body. Secondly, he is able to fire volleys of",
"devastating green comets that tear through armor and flesh alike. And to top",
"it all off, he vaporizes in a viscous green cloud upon death. Underneath all",
"that, though, he'll go down much like the rest of his brethren. Unfortunately,",
"the archon does take a few more hits to beat, and it's much harder to dodge his",
"attacks, so you still better have your wits about you when you confront him."},
//Pyrodemon
{"These burning beasts' lust for fire has driven them to utter insanity. They",
"love to kill their victims in the most pyromanic ways, even by exploding into",
"a ball of fire and reappearing immediately in front of their target. They pay",
"no mind to any of their nearby brethren, and fire explosive fireballs in every",
"direction they possibly can, just to get a chance to see you burn. Never get",
"too close!","",""},
//Azazel
{"Not much is known about the Azazel, mainly due to our unfortunate observers",
"getting fried every time they try to gather more tactical information on it.",
"Your best bet when you see it rear its ugly head is to run like hell in the",
"other direction. If you're standing too close, you'll get caught in the range",
"of its powerful energy discharge attack and get char-grilled. Unload as much",
"ammo as possible on it as you run, 'cause it'll be throwing a plethora of",
"projectiles your way, some of which are nigh-impossible to dodge. Easily the",
"most dangerous demon you will deal with in your missions."},
//---FATSOS---//
//Mancubus
{"The embodiment of gluttony, one of the seven deadly sins. Basically, the",
"mancubus is the hellish reincarnation of that fat kid from school that gorged",
"himself on Twinkies. And now they've given him a pair of high-powered cannons",
"to compensate for the fact that he can barely move. All that fat will absorb",
"most of the damage you do to it, but luckily, he can't really aim very well.","","",""},
//Hectebus
{"The hectebus can probably best be described as his lower cousin tanked up on a",
"substantial amount of illegal substances. A considerable proportion larger",
"than the mancubus, this colossus has been known to reduce stronghold defenders",
"to primordial slime in an eyeblink with his extremely powerful twin cannons.",
"His horribly bulky structure makes him a formidably difficult foe to overcome,",
"so make sure you have a powerful weapon on you before confronting him.","",""},
//---SPIDERS---//
//Arachnotron
{"Every arachnotron wants to be a spider mastermind someday. For now, they have",
"a plasma gun that really hurts if you stay still for too long. If you want to",
"kill these effectively, use hard heavy shots, and stay out of the plasma",
"stream. A few rockets will do the trick.","","","",""},
//Fusion Spider
{"The arachnotron got a weapon upgrade. Instead of a slow-fire plasma cannon,",
"they now have a fusion energy launcher, which releases a field of slow-moving,",
"high damage energy projectiles in an outward spread pattern. These walls of",
"death crawl forward at an inexorable rate, and are extremely hard to avoid",
"unless you have some damn good cover. Be sure to note also that the fusion",
"spider is now slightly harder to kill than its less dangerous, but equally",
"annoying counterpart.",""},
//---VILES---//
//Hellion
{"These nasty imp/arch-vile-like demons come from the deepest caverns of Hell.",
"They have no hesitation in attacking you with deadly flame bursts. They",
"usually come in large hordes, much like shadows, and are just as fast. So our",
"advice is to use an effective, rapid-fire weapon in order to take them down as",
"fast as possible.","","",""},
//Archvile
{"If you thought battling demons ONCE was bad, then this guy will try to make",
"sure you face them again! And to make things worse, he's got an explosive fire",
"attack that will hurl you into the air, doing heavy damage. Quick termination",
"with extreme prejudice is advised.","","","",""},
//Diabolist
{"Some suspect the diabolist is a lesser incarnation of Satan himself. Anything",
"within this bastard's attack range (that is, anything within his line of",
"sight) soon turns to ash. He has several devastating attacks, all of which",
"involve burning, heat, flames, fire...you get the idea. When you see him, run",
"for cover. You've got nought else to do if you don't have a weapon equally",
"good at clearing a room as he is.","",""},
//---BOSSES---//
//Spider Mastermind
{"Mechanical spider, except with half the number of legs, but still deadly. The",
"best way to kill her is to attack from far away, and with a BFG. She does not",
"suffer explosions like other monsters do. Rumor has it that these brainpans-",
"on-legs used to take more of a beating than they do these days, but let's just",
"assume that we've gotten better at it. It's better for morale.","","",""},
//Spider Demolisher
{"Dear God, save us all. The demons got ahold of our BFG technology, and this",
"is the result. One of the most powerful demons we've seen in a long while,",
"only made far worse by double the usual firepower - and that doesn't even",
"count the destructive capabilities of the BFG they mounted on the damn thing!",
"Rest assured, marine, we'll make damned sure you get enough firepower to take",
"this thing on, or else you're not going to be the only thing we lose!","",""},
//Cyberdemon
{"Take a regular demon, supersize him, give him a rocket launcher and other",
"cybernetic attachments, and this guy is the result. The only way to fight this",
"guy is with good reflexes and a super fast gun. His rockets are hard to dodge,",
"and he doesn't feel much pain. He's also immune to explosions, except when he",
"suffers a direct impact, so rockets and pyro cannons do far less damage to him",
"than they do to other creatures. Plasma rifles are most effective.","",""},
//Terminator
{"Hard to differentiate between demon and machine, the terminator is probably",
"the toughest enemy you will ever face during your missions. Its vital systems",
"are not only protected by heavy armor, but also by powerful invisible energy",
"fields, which allow it to absorb huge amounts of physical damage. In addition,",
"it seems to have a nigh infinite arsenal of destructive weaponry. With arm",
"cannons that launch fast, explosive energy projectiles, missiles that home in",
"on their targets, a chaingun, AND a missile launcher, you must approach this",
"goliath with extreme caution, and perhaps a very big gun."},

};
